input("Please enter the Product Code: ")
input("Please enter the Product Name: ")
input("Please enter the Current Stock: ")
input("Please enter the Product Sale Price: ")
input("Please enter the Product Manufacture Cost: ")
input("Please enter estimated monthly production: ")
